vec(2) {
  object(HH\Asio\WrappedException)#5 (1) {
    ["exception":"HH\Asio\WrappedException":private]=>
    object(Exception)#3 (8) {
      ["message":protected]=>
      string(0) ""
      ["string":"Exception":private]=>
      string(0) ""
      ["code":protected]=>
      int(0)
      ["file":protected]=>
      string(128) "/home/ubuntu/user-documentation-2018-09-07/guides/hack/09-asynchronous-operations/10-exceptions-examples/wrapping-exceptions.php"
      ["line":protected]=>
      int(9)
      ["trace":"Exception":private]=>
      array(3) {
        [0]=>
        array(3) {
          ["file"]=>
          string(128) "/home/ubuntu/user-documentation-2018-09-07/guides/hack/09-asynchronous-operations/10-exceptions-examples/wrapping-exceptions.php"
          ["line"]=>
          int(17)
          ["function"]=>
          string(78) "Hack\UserDocumentation\AsyncOps\Exceptions\Examples\Wrapping\exception_thrower"
        }
        [1]=>
        array(3) {
          ["file"]=>
          string(128) "/home/ubuntu/user-documentation-2018-09-07/guides/hack/09-asynchronous-operations/10-exceptions-examples/wrapping-exceptions.php"
          ["line"]=>
          int(27)
          ["function"]=>
          string(80) "Hack\UserDocumentation\AsyncOps\Exceptions\Examples\Wrapping\wrapping_exceptions"
        }
        [2]=>
        array(1) {
          ["function"]=>
          string(65) "Hack\UserDocumentation\AsyncOps\Exceptions\Examples\Wrapping\main"
        }
      }
      ["previous":"Exception":private]=>
      NULL
      ["userMetadata":protected]=>
      NULL
    }
  }
  object(HH\Asio\WrappedResult)#8 (1) {
    ["result":"HH\Asio\WrappedResult":private]=>
    int(2)
  }
}
